/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    "overview",
    "map",
    {
      type: "category",
      label: "🛠️ Pre-Requisites",
      items: [
        { type: "doc", id: "vssub", className: "vscode" },
        { type: "doc", id: "setupm365", className: "m365" },
        { type: "doc", id: "linkazuresub", className: "azure" },
      ],
    },

    {
      type: "category",
      label: "Identity",
      className: "azuread",
      items: [
        {
          type: "category",
          label: "Cloud or Hybrid",
          className: "azuread",
          link: {
            type: "doc",
            id: "cloudorhybrid",
          },
          items: [
            { type: "doc", id: "clouddeploy", className: "azuread" },
            {
              type: "category",
              label: "Hybrid Deployment",
              className: "hybrid",
              link: {
                type: "doc",
                id: "hybriddeploy",
              },
              items: [
                { type: "doc", id: "cloudsync", className: "connectsync" },
              ],
            },
          ],
        },
        { type: "doc", id: "pim", className: "pim" },
        { type: "doc", id: "securetenant", className: "ca" },
        { type: "doc", id: "license", className: "license" },
        { type: "doc", id: "pswdprotect", className: "pswdprotect" },
        {
          type: "category",
          label: "Passwordless",
          className: "passwordless",
          items: [
            { type: "doc", id: "pswdlesspsi", className: "psi" },
            { type: "doc", id: "pswdlesscba", className: "cba" },
            { type: "doc", id: "pswdlesswhfb", className: "azure" },
            { type: "doc", id: "pswdlessfido2", className: "azure" },
          ],
        },
        {
          type: "category",
          label: "Applications",
          className: "allapps",
          items: [
            { type: "doc", id: "saasapp", className: "apps" },
            { type: "doc", id: "appproxy", className: "appproxy" },
          ],
        },
        {
          type: "category",
          label: "Governance",
          className: "governance",
          items: [
            { type: "doc", id: "goventmgmt", className: "entmgmt" },
            { type: "doc", id: "govaccrev", className: "accessreview" },
            { type: "doc", id: "govlcw", className: "lcw" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Devices",
      className: "intune",
      items: [
        { type: "doc", id: "intappprot", className: "intune" },
        { type: "doc", id: "intmdm", className: "intune" },
      ],
    },
    {
      type: "category",
      label: "Threat Protection",
      className: "defender",
      items: [
        { type: "doc", id: "defidentity", className: "defender" },
        { type: "doc", id: "defo365", className: "defender" },
        { type: "doc", id: "defendpoint", className: "defender" },
        { type: "doc", id: "defcloudapp", className: "defender" },
      ],
    },
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  //docsSidebar2: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
